# Site Settings
title:               A deep learning approach to solar-irradiance forecasting in sky-videos
tagline:
description:         A deep learning approach to solar-irradiance forecasting in sky-videos
baseurl:             #"/Lagrange"
url:               https://samarth-b.github.io/ #"https://lenpaul.github.io"
github:
  url:              https://samarth-b.github.io/skycamIrr/ #"https://lenpaul.github.io/Lagrange"
author:
  name:              "Samarth Bharadwaj"
  org:              "IBM Research India"
  email:             "samarth.b@in.ibm.com"
  twitter:           "samarth_b"
  instagram:         ""
  github:            "https://github.com/samarth-b/skycamIrr"
  facebook:          ""
  linkedin:          "/samarthbh/"
navigation:
- title: About
  url: /about
- title: Archives
  url: /Archives

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]

theme: jekyll-theme-cayman